os: linux
dist: bionic
language: python
jobs:
  include:
    - name: "Python 2.7 on Bionic"
      python: 2.7
    - name: "Python 3.7 on Bionic"
      python: 3.7

# command to install dependencies
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - python setup.py install

script: pytest
